# Generated by Django 3.2.5 on 2021-08-10 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='availabilitystatus',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='property',
            name='contacts',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.location'),
        ),
    ]
