# Generated by Django 3.2.5 on 2021-12-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20211203_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='availabilitystatus',
        ),
    ]
