# Generated by Django 3.2.5 on 2021-12-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_property_availabilitystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='email',
            field=models.TextField(default='n/a'),
        ),
    ]
