# Generated by Django 3.2.5 on 2021-12-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='noofrooms',
            field=models.TextField(default='unspecified'),
        ),
    ]
