# Generated by Django 3.2.5 on 2021-12-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_staffrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrequest',
            name='message',
        ),
    ]
